fix: add length filter for tantivy token (#8311)
Add two new ENV:
```
ZO_INVERTED_INDEX_MIN_TOKEN_LENGTH=2
ZO_INVERTED_INDEX_MAX_TOKEN_LENGTH=64
```
The previous version we only remove the tokens longer than `64`, didn't
remove the small tokens.

Now, we support both remove mini token and huge token.

Why we got error like this:
```
thread 'job_runtime' panicked at /index.crates.io-1949cf8c6b5b557f/tantivy-stacker-0.3.0/src/memory_arena.rs:205:9:
```
Because Tantivy use int32 for memory address, it can't generate data
page large than 4GB, and we only generate one segment file for one
parquet file in OpenObserve, it caused one problem, if the parquet is
very large that will generate a lot of tokens, at the end, the Tantivy
segment will exceeds the limit then paniced.

This PR improved the token generated, will auto remove:
- the single char token, less than `2`.
- large token that more than `64` chars.

With these changes we can succeeded generate `5GB` parquet file and the
Tantivy file.